prefix sg:<http://scigraph.springernature.com/ontologies/core/> 

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
select ?chapter ?doi ?title ?name ?orgId ?orgName ?year ?conf ?confName ?confSub ?edition ?chapter
where { 
	?conf a sg:Conference .
    ?edition sg:title ?confName . 
    ?edition sg:subtitle ?confSub .
    ?edition sg:hasConference ?conf .
    ?edition sg:bookType "Proceedings" .
    ?chapter sg:hasBookEdition ?edition .
    ?chapter sg:doi ?doi .
    ?chapter a sg:BookChapter .
    ?chapter sg:title ?title .
    ?chapter sg:hasContribution ?author .
    ?chapter sg:copyrightYear ?year .
    ?author sg:publishedName ?name .
    ?chapter sg:hasContributingOrganization ?orgId .
    ?orgId rdfs:label ?orgName .
}
LIMIT 10
